name: test_gpu_install_env
channels:
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python
  - openblas 
  - lapack 
  - liblapacke
  - wget
  - gsl
  - hdf5
  - numpy=1.*
  - scipy
  - Cython
  - tqdm
  - jupyter
  - ipython
  - h5py
  - requests
  - matplotlib
